# Generated by Django 3.2.8 on 2022-09-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.PositiveIntegerField(db_column='cid', default=0, verbose_name='internal_id')),
                ('voice', models.CharField(db_column='voice', default='', max_length=128, verbose_name='narrative_voice')),
                ('author', models.CharField(db_column='author', default='', max_length=128, verbose_name='author')),
                ('character_id', models.PositiveIntegerField(db_column='char_id', default=0, verbose_name='character_id')),
                ('name', models.CharField(db_column='name', default='', max_length=128, verbose_name='name')),
                ('title', models.CharField(db_column='title', default='', max_length=256, verbose_name='title')),
                ('year', models.CharField(db_column='year', default='', max_length=128, verbose_name='year')),
                ('violence', models.CharField(db_column='violence', default='', max_length=128, verbose_name='violent_behaviour')),
                ('race', models.CharField(db_column='race', default='', max_length=128, verbose_name='race')),
                ('gender', models.CharField(db_column='gender', default='', max_length=128, verbose_name='gender')),
                ('urban', models.CharField(db_column='urban', default='', max_length=128, verbose_name='urban')),
                ('sthreat', models.CharField(db_column='sthreat', default='', max_length=128, verbose_name='sexual_threat')),
                ('sdesire', models.CharField(db_column='sdesire', default='', max_length=128, verbose_name='object_of_sexual_desire')),
                ('death', models.CharField(db_column='death', default='', max_length=128, verbose_name='death')),
                ('suicide', models.CharField(db_column='suicide', default='', max_length=128, verbose_name='suicide')),
                ('migration', models.CharField(db_column='migration', default='', max_length=128, verbose_name='migration_north')),
                ('deterritorialization', models.CharField(db_column='deterritorialization', default='', max_length=128, verbose_name='deterritorialization')),
                ('oppression', models.CharField(db_column='oppression', default='', max_length=128, verbose_name='dispossessed_oppressed')),
                ('revolt', models.CharField(db_column='revolt', default='', max_length=128, verbose_name='revolt')),
                ('assimilation', models.CharField(db_column='assimilation', default='', max_length=128, verbose_name='tries_to_assimilate')),
                ('guide', models.CharField(db_column='guide', default='', max_length=128, verbose_name='guide')),
                ('craziness', models.CharField(db_column='craziness', default='', max_length=128, verbose_name='craziness')),
                ('children_metis', models.CharField(db_column='children_metis', default='', max_length=128, verbose_name='have_metis_children')),
                ('children_native', models.CharField(db_column='children_native', default='', max_length=128, verbose_name='have_native_children')),
                ('sprituality', models.CharField(db_column='spirituality', default='', max_length=128, verbose_name='spirituality_wisdom')),
                ('allegory', models.CharField(db_column='allegory', default='', max_length=128, verbose_name='allegory')),
                ('age_old', models.CharField(db_column='old_age', default='', max_length=128, verbose_name='old_age')),
            ],
            options={
                'db_table': 'characters',
            },
        ),
    ]
