# Generated by Django 3.2.8 on 2022-09-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterdetails',
            options={'verbose_name_plural': 'characters'},
        ),
    ]
